# Development override for docker-compose.yml
version: '3.8'

services:
  backend:
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: python -m flask run --host=0.0.0.0 --port=5000

  chatbot:
    volumes:
      - ./chatbot:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: python -m flask run --host=0.0.0.0 --port=5001

  frontend:
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0 --port=5174

  # PgAdmin for database management (optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: invoice_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@invoice.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - invoice_network
    profiles:
      - dev-tools

  # Mongo Express for MongoDB management (optional)
  mongo-express:
    image: mongo-express:latest
    container_name: invoice_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb
    networks:
      - invoice_network
    profiles:
      - dev-tools