# Configuration for Rasa NLU & Core.
# Documentation: https://rasa.com/docs/rasa/model-configuration/

version: "3.1"

recipe: default.v1

language: vi

pipeline:
  # Vietnamese language support
  - name: SpacyNLP
    model: "vi_core_news_lg"
  - name: SpacyTokenizer
  - name: SpacyFeaturizer

  # Character-level features for Vietnamese
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4

  # Intent classification
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true

  # Entity extraction
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true

  # Fallback handling
  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1

policies:
  # Machine Learning policies
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 100
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true

# Assistant configuration
assistant_id: invoice_chatbot_vi
